name: ci

on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
    steps:
      - name: SCM
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # Install and test Fronted
      - run: npm --prefix $PWD/client/ install
      - run: npm run build --if-present
      - run: CI=true npm --prefix $PWD/client/ test --coverage --watchAll
      - name: Upload coverage to Codecov
        if: matrix.node-version == '15.x'
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella

  docker:
   # Triggered only ci was success
    needs: ci
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ../client    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    #  - name: Set client as working directory
    #    working-directory: ./client 
    #    run: cp .env.dev .env
        # build against more platforms
      - name: List Directories
        run: ls -ltrh       
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        # create and boot a builder that can be used in the following steps of your workflow
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"     

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: eatthestake/client:latest
